### ISSUE TITLE
Anudatta svara placing

### ISSUE THREAD

**Issue by karthik-holla** [Sandhi-IITBombay/Shobhika#6]
I have attached two pdf consisting of rigveda pada typed with shobhika font where I feel
the anudatta svaras are not consistent. I feel if we lower the position of the anudatta svaras
for all the alphabets it will be consistent. And even in the svarita if the marking is little bigger then
it will be better.Thank You.
[output.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/816120/output.pdf)
[anudatta.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/816121/anudatta.pdf)

**Comment by ijya** [comment]
The positioning of the anudatta svaras is predefined and cannot be dynamic in any font. The anudatta svaras in Shobhika are positioned at a fixed distance from the bottom of the glyph. Therefore, any difference in anudatta heights has to do with the difference in glyph heights (usually involving glyphs with tails like द and इ). Additionally, if a maatra occurs below the character, then the svara is placed below it. Unnecessarily increasing the gap between the glyph and the svara so that the anudattas look uniform is not a good design practice and would also result in unnecessarily large line gaps in all cases.

**Comment by jamadagni** [comment]
@ijya Whether anudatta-s should all be placed at a consistent position or not despite the existence of descenders is a matter of taste. Higher protocols like font features are available nowadays to tackle this, but they take much more work to implement. If you decide that it is outside the scope of the current project, then you should close this issue.
